# SPDX-FileCopyrightText: 2025 Contributors to the CitrineOS Project
#
# SPDX-License-Identifier: Apache-2.0

services:
  citrine-ui:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000
